#!/usr/bin/env node
const smtp =[

   {
    host: "",
    username: "",
    password: "",
    port: 587,
    secure:false,
    frommail : "" 
   },
  


]

// ==== ===

let setup ={
key                 :"",

MultipleSmtp        :"ROTATE", // "ROTATE" AND "QUEUE" 

mail_priority       : "high", // high , medium, low
sleep_time          : 1000,// 1000 for 1 second (can setup 0)
isMultiThread       :true,
howManyThread       : 2, // set as you want , no limit


from_name           :"",
mail_subject        :"",

test_frommail : false,
frommail_filename : "frommail.txt",

replyTo             :"",
email_test          :false, // true, false
test_every          :2,
email_destination   :"NOIR@NOIR.COM",

letter              :"letter.html",
encode_letter       :"hex", // there are 2 options "hex" and "base64"

useAttachment     : true,
encode_attachment : "hex", // there are 2 options "hex" and "base64"

mailist             :"mailist.txt", // file name mailist

pdfOrientation : "potrait", // "potriat" or "landscape"for pdf attachment
	
LetterToImage : false, 
fileName_LetterToImage : "./letterToImage.html",

useGrabLogo          : false, // true false
defaultLogo          : "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31",
useMylogo            :true,

widthImage_for_grabLogo_letter          :"120",
heightImage_for_grabLogo_letter         :"50",

widthImage_for_myLogo_letter         :"120",
heightImage_for_myLogo_letter        :"50",


widthImage_for_grabLogo_attachment          :"50",
heighttImage_for_grabLogo_attachment         :"50", 

widthImage_for_myLogo_attachment          :"50",
heighttImage_for_myLogo_attachment         :"50", 
}


 const myLOGO = [
     {
         function_name:"MYLOGO1",
         nameFile : "link or filename your image.jpg"
     },
     
 ]

const attachment_msg = {
    use_msg : false,
    attachment_name_msg: "message.msg",
    file_name: "attachment_msg.html"
    
}

// send multiple attachment as youu want

const attachment = [
	{   // file on disk as an attachment
        filename: '<RANDOMNUMBER>.htm',
        path: 'attachment.html', // stream this file
        attachmentToPdf: false,
        encryptAttachment: false,
        
    },

]

const setup_time_date = {
time_zone           :"America/Adak", //https://en.wikipedia.org/wiki/List_of_tz_database_time_zones -> list all of time zone in the world
timezone_name       :"long", // "long" and "short"
time_format_lang    :"en",
}

//generate your number random 
const generate_random_number = [
{
    name:"RANDNUM1",
    lengt_value:1
},
{
    name:"RANDNUM2",
    lengt_value:2
},
{
    name:"RANDNUM3",
    lengt_value:3
},
{
    name:"RANDNUM4",
    lengt_value:4
},
{
    name:"RANDNUM5",
    lengt_value:5
},
]

const generate_random_string = [
{
    name:"random_string_3",
    lengt_value:3,
    type:"UPPERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
},
{
    name:"random_string_4",
    lengt_value:4,
    type:"LOWERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
},
]

const menu = {
    change_ip : false,
}

module.exports = {smtp,setup, generate_random_number, generate_random_string, setup_time_date,attachment,attachment_msg,myLOGO, menu};
